name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name : Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Install dependencies
        run: |
          yarn install

      # - name: access to secrets
      #   run: | 
      #     echo "NEXT_PUBLIC_GRAPHQL_API_URL=${{ secrets.API_END_POINT }}" >> .env         

      - name: create robot.txt & sitemap.xml
        run: sh script/generate-sitemap.sh

      - name: Build the project
        run: |
          yarn build 

      - name: 원격 접속 배포
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_IP }}        
          username: ${{ secrets.VPS_USERNAME }}     
          password: ${{ secrets.VPS_PASSWORD }}    
          port: 22                             
          script: |
            echo "Deploying to VPS server"
            cd public_html
            git pull origin main
            yarn install 
            yarn build
            pm2 list
            yarn start-pm2