export const TRANSITION_STATE = 'TRANSITION_STATE';
export const PREV_URL_STATE = 'PREV_URL_STATE';
export const CURRENT_URL_STATE = 'CURRENT_URL_STATE';
export const EPISODE_COLOR_STATE = 'EPISODE_COLOR_STATE';
